# Generated by Django 3.2.12 on 2022-09-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmessages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regster',
            new_name='Register',
        ),
    ]
